### ISSUE TITLE
Zoom in limits the screen 

### ISSUE THREAD

**Issue by deepseek** [PRImA-Research-Lab/prima-page-viewer#12]
@chris1010010 

when I zoom more than 100% I can't scroll down, somehow the scroll doesn't adjust to the zoom after 100%

**Comment by chris1010010** [comment]
Hi, what platform is it? And what's the image size? Works for me on Win

**Comment by deepseek** [comment]
Linux mint 19.2
```
home@home-desktop:~$ java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```

**Comment by chris1010010** [comment]
And the image size?
So no scrolling works (via scroll bar, via mouse wheel, via click + drag)? 
You said "can't scroll down", can you scroll to the right?

**Comment by deepseek** [comment]
@chris1010010 
demo contains the xml+image+small video
[demo.zip](https://github.com/PRImA-Research-Lab/prima-page-viewer/files/4298103/demo.zip)
notice in the demo, the more i zoom, the lesser the ability to scroll down. until you can't scroll down.
most likely there is a limit on the screen size after you zoom further than 100%

**Comment by chris1010010** [comment]
Seems to be a problem with the Linux version then.
I can zoom in all the way to the page number in Win without problem.

![image](https://user-images.githubusercontent.com/7868102/76082337-08ca3900-5fa3-11ea-8826-6c95dec6dda0.png)

**Comment by deepseek** [comment]
hmmmmm....
you might be right, OpenJDK might act funny at times.

**Comment by chris1010010** [comment]
Might have to do with the SWT library. If I were to start the PageViewer today I'd probably use Swing. Let's leave the issue open, perhaps someone else has input...

**Comment by deepseek** [comment]
@chris1010010 that's weird, on linux i have tested using oracle java and still having this issue.
On Windows everything seems fine??

**Comment by chris1010010** [comment]
The problem is the swt library the code is based on (see lib folder). Independent of the Java version, it will always use that library (which is old). I haven't checked if there's a new version, but I doubt it
