### ISSUE TITLE
textlines not displayed

### ISSUE THREAD

**Issue by bertsky** [PRImA-Research-Lab/prima-page-viewer#13]
I believe I found a bug in whether or not PageViewer enables the `Lines` button in the main toolbar.

When the only textlines of the document are on a non-toplevel region (e.g. a table), then the page will be shows as if it had none.

The cause seems to be that `DISPLAY_TEXTLINES` is only enabled when `org.primaresearch.dla.page.layout.PageLayout.hasLowLevelTextObject()` returns true for `TextLine`, but that function does not enter the **recursive** region hierarchy.

**Comment by bertsky** [comment]
(So maybe this issue should be moved to prima-core-libs?)

**Comment by chris1010010** [comment]
Should work now, please test

**Comment by bertsky** [comment]
> Should work now, please test

It does (1.4.05) – thank you very much!
