### ISSUE TITLE
show baselines

### ISSUE THREAD

**Issue by bertsky** [PRImA-Research-Lab/prima-page-viewer#17]
Today I was surprised to learn that PageViewer does not visualise `TextLine/Baseline`.

Wouldn't be much more than checking for `line.getBaseline()` in `DocumentImageView.drawTextlines()`, and using a new `DrawingHelper.drawMultiline` to display it, right?

**Comment by chris1010010** [comment]
The world is full of surprises...
:-)

**Comment by bertsky** [comment]
> The world is full of surprises...
> :-)

Sure, but how do I ever get to see a PAGE baseline then? Is Aletheia the only tool that shows them? Or is AletheiaWeb, too?

Also, on my suggestions – assuming I would be able to get the build system for _this_ package – is that the way to go, or am I missing something?

**Comment by chris1010010** [comment]
Just Aletheia at the moment

**Comment by bertsky** [comment]
> Just Aletheia at the moment

I see. Do you happen to know if this works with `wine`? (It should, you know, since _in vino veritas_ ...)

> Also, on my suggestions – assuming I would be able to get the build system for _this_ package – is that the way to go, or am I missing something?

Still thinking about a PR but waiting for your approval.

**Comment by chris1010010** [comment]
Merged in the baseline code

**Comment by bertsky** [comment]
> Merged in the baseline code

Thanks, but 5113c38b37a9776d02c2401df14c405987dc3230 is not a merge, it's a copy, modify and paste. I'll have to rebase now. If you had just asked me to split my PR I would have done so (as I [said](https://github.com/PRImA-Research-Lab/prima-page-viewer/pull/18#issuecomment-727071980))...

Also, I wonder why you always couple changes of source files with fully regenerated apidoc HTMLs in your commits. This makes it much harder to view them and browse history. If apidoc needs to be in the same repo, please at least commit the HTMLs separately.

**Comment by chris1010010** [comment]
Ok, yes, it was a manual merge.
Code and JavaDoc are generated. I use a separate code base in SVN. Should move at some point, no time though

**Comment by bertsky** [comment]
Oh, I see – that explains it. But perhaps you could do something like

    git add "*.java" && git commit -m "changes"
    git add -A && git commit -m "javadoc"

?
