### ISSUE TITLE
XML Load Error: An XML Loading error occurred

### ISSUE THREAD

**Issue by YHDASHEN** [PRImA-Research-Lab/prima-page-viewer#22]
Hi everyone, I'm facing with a problem that I cannot open the Page XML files with "JPageViewer 1.4 (Windows, 64 bit)".  I can only open XML file in the example folder.

Page XML files are the output of OCR-D workflow:
`
ocrd process   
"sbb-binarize -I OCR-D-IMG -O OCR-D-BIN -P model default"   
"anybaseocr-crop -I OCR-D-BIN -O OCR-D-CROP"   
"tesserocr-segment -I OCR-D-CROP -O OCR-D-SEG -P shrink_polygons true -P padding 4"  
 "segment-extract-glyphs -I OCR-D-SEG -O OCR-D-GLYPHS -P transparency true"
`
I'm using WSL1 and Ubuntu 18.04 LTS on Windows 10. Here is my workplace folder, I can't open these XML files.
![捕获](https://user-images.githubusercontent.com/84343950/118536277-d0e48700-b74b-11eb-88d9-2bb6caeb4930.PNG)

**Comment by kba** [comment]
Can you please post the PAGE-XML or even better the whole OCR-D workspace, so we can debug this?

**Comment by YHDASHEN** [comment]
Firstly I created a workplace with such line:
`ocrd-import --nonnum-ids --ignore --render 300 /mnt/d/workplace/OCR-D-IMG`

Then I run the OCR-D workflow above and get XML files for the 4 images(Images from example in this Setup Guide https://ocr-d.de/en/setup). And here is one PAGE-XML file from folder "OCR-D-CROP"
`
<?xml version="1.0" encoding="UTF-8"?>

-<pc:PcGts pcGtsId="OCR-D-CROP_OCR-D-CROP_0001" xsi:schemaLocation="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15 http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15/pagecontent.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pc="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15">


-<pc:Metadata>

<pc:Creator>OCR-D/core 2.23.3</pc:Creator>

<pc:Created>2021-05-17T15:27:56.431326</pc:Created>

<pc:LastChange>2021-05-17T15:27:56.431326</pc:LastChange>


-<pc:MetadataItem value="ocrd-sbb-binarize" name="preprocessing/optimization/binarization" type="processingStep">


-<pc:Labels externalId="parameters" externalModel="ocrd-tool">

<pc:Label value="default" type="model"/>

<pc:Label value="page" type="operation_level"/>

</pc:Labels>


-<pc:Labels externalId="version" externalModel="ocrd-tool">

<pc:Label value="0.0.7" type="ocrd-sbb-binarize"/>

<pc:Label value="2.23.3" type="ocrd/core"/>

</pc:Labels>

</pc:MetadataItem>


-<pc:MetadataItem value="ocrd-anybaseocr-crop" name="preprocessing/optimization/cropping" type="processingStep">


-<pc:Labels externalId="parameters" externalModel="ocrd-tool">

<pc:Label value="0.04" type="colSeparator"/>

<pc:Label value="0.3" type="maxRularArea"/>

<pc:Label value="0.05" type="minArea"/>

<pc:Label value="0.01" type="minRularArea"/>

<pc:Label value="0.75" type="positionBelow"/>

<pc:Label value="0.4" type="positionLeft"/>

<pc:Label value="0.6" type="positionRight"/>

<pc:Label value="10.0" type="rularRatioMax"/>

<pc:Label value="3.0" type="rularRatioMin"/>

<pc:Label value="0.95" type="rularWidth"/>

<pc:Label value="10" type="padding"/>

</pc:Labels>


-<pc:Labels externalId="version" externalModel="ocrd-tool">

<pc:Label value="1.3.0" type="ocrd-anybaseocr-crop"/>

<pc:Label value="2.23.3" type="ocrd/core"/>

</pc:Labels>

</pc:MetadataItem>

</pc:Metadata>


-<pc:Page imageHeight="3263" imageWidth="1995" imageFilename="OCR-D-IMG_0001.jpg">

<pc:AlternativeImage comments=",binarized" filename="OCR-D-BIN/OCR-D-BIN_OCR-D-BIN_0001.IMG-BIN.png"/>

<pc:AlternativeImage comments=",binarized,cropped" filename="OCR-D-CROP/OCR-D-CROP_OCR-D-CROP_0001-IMG.png"/>


-<pc:Border>

<pc:Coords points="424,564 1376,564 1376,2955 424,2955"/>

</pc:Border>

</pc:Page>

</pc:PcGts>
`
I don't know whether that's enough for debugging, thank you so much in advance!

**Comment by YHDASHEN** [comment]
I know where my problem is. After I open the PAGE XML file, I need to open the corresponding image to show the layout. I missed the information in Gitter so I stuck there a little bit. I think it would be better if there is a Message box that can give a feedback when successfully loading the XML file and tell the user what to do next.
