### ISSUE TITLE
Drag & Drop feature for opening a file/files

### ISSUE THREAD

**Issue by mrocr** [PRImA-Research-Lab/prima-page-viewer#4]
@chris1010010 @jakesebright 
Can you add the ability to drag and drop to open a file or files in Page Viewer.

**Comment by chris1010010** [comment]
I can have a look

**Comment by mrocr** [comment]
Thanks

**Comment by mrocr** [comment]
@chris1010010 The drag & drop feature, do it.
 Now!
:)

**Comment by chris1010010** [comment]
Done.
I think.
Code committed, but no new release right now

**Comment by mrocr** [comment]
god bless you
