### ISSUE TITLE
new version supporting 2019 namespace

### ISSUE THREAD

**Issue by bertsky** [PRImA-Research-Lab/prima-page-viewer#5]
Are there current plans to make a new release for the `2019-07-15` version? Can I help with a PR?

**Comment by chris1010010** [comment]
I'm on it. Need to update the core libs first and do some testing ideally.

**Comment by bertsky** [comment]
Splendid! Thanks for responding so quickly.

**Comment by chris1010010** [comment]
There's a new release. I did some basic testing, but not super thorough...

**Comment by bertsky** [comment]
Thanks @chris1010010! One more thing, there are no building instructions here, and no new binaries on the PRImA website. There is one `.project` which opens in Eclipse JDT, but it does not build:
```
Description	Resource	Path	Location	Type
Project 'JAletheia' is missing required Java project: 'PrimaBasic'	JAletheia		Build path	Build Path Problem
Project 'JAletheia' is missing required Java project: 'PrimaDla'	JAletheia		Build path	Build Path Problem
Project 'JAletheia' is missing required Java project: 'PrimaIo'	JAletheia		Build path	Build Path Problem
Project 'JAletheia' is missing required Java project: 'PrimaMaths'	JAletheia		Build path	Build Path Problem
Project 'JAletheia' is missing required library: 'lib/swt.jar'	JAletheia		Build path	Build Path Problem
The project cannot be built until build path errors are resolved	JAletheia		Unknown	Java Problem
```

Regarding `swt.jar`, I tried to copy various versions (those from `eclipse/plugins/org.eclipse.swt*`, and those from `libswt-gtk-4-java` Ubuntu pkg) into `lib/swt.jar`, but that did not help. 

Being an absolute stranger to Eclipse and Java builds, how do I make this work?

**Comment by chris1010010** [comment]
There are binaries in the release section in the GitHub repo.
I should add build instructions. You'll need the prima core libs (it's another GitHub repo). You can use the swt jar from the release

**Comment by bertsky** [comment]
> There are binaries in the release section in the GitHub repo.

Me bad – found it, thanks!
