### ISSUE TITLE
JPageViewer ignores command line parameter of image file name

### ISSUE THREAD

**Issue by waldekb** [PRImA-Research-Lab/prima-page-viewer#9]
JPageViewer.jar when run from command line (on windows) ignores second parameter of image file name and takes it from XML file from node:
<Page imageFilename="00000190.jpg" imageWidth="2309" imageHeight="3166">

This is a problem when I try to open ALTO and corresponding image files from command line, because ALTO doesn't contain imageFilename and second parameter is still ignored.

**Comment by chris1010010** [comment]
Should be fixed now
